### PR TITLE
Feat/remove user stories+update repo

### PR DESCRIPTION
**Pull request by moT01**
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721

### CODE REVIEW

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳

**Review by RandellDawson — APPROVED** [review]
LGTM - We can merge this one once the changes from https://github.com/freeCodeCamp/freeCodeCamp/pull/40217 hit production.

**Comment by RandellDawson** [comment]
Merging this one now, since the changes from https://github.com/freeCodeCamp/freeCodeCamp/pull/40217 have hit production.

**Comment by RandellDawson** [comment]
@moT01 Thanks for your contribution as always.

**Pull request merged**
